---
- name: Generate Hosts File
  hosts: worker
  become: true
  gather_facts: true
  tasks:
    - name: Generated token - 1.
      local_action: shell sed -n 83,84p ./token > ./workertoken
    - name: Copy master token
      copy:
        src: /opt/k8s/workertoken
        dest: /tmp/join-worker-command.sh
        owner: root
        group: root
        mode: '0777'
    - name: Add new Kubernetes master member
      command: sh /tmp/join-worker-command.sh
